//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformedProteomics.Scoring.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InformedProteomics.Scoring.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Charge	3
        ///BinSize	402	402	402	402	402	402	402	402	402	402	402	402	402	402	402	402	402	402	402	402	402	402	402	402	402	402	402	402	402	402	427
        ///BinEdges	0	951.538931745
        ///RankProbabilities
        ///MaxRanks	151
        ///y	64	95	96	69	69	44.33	44.33	44.33	34.33	34.33	34.33	20.5	20.5	20.5	20.5	14	14	14	14	10.75	10.75	10.75	10.75	8	8	8	8	8	6	6	6	6	6	6	6	6	6	6	4.8	4.8	4.8	4.8	4.8	3.4	3.4	3.4	3.4	3.4	2.4	2.4	2.4	2.4	2.4	5	5	5	5	5	5	2.83	2.83	2.83	2.83	2.83	2.83	1.33	1.33	1.33	1.33	1.33	1.33	1.83	1.83	1.83	1.83	1.83	1.83	2.17	2.17 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HCD_Trypsin {
            get {
                return ResourceManager.GetString("HCD_Trypsin", resourceCulture);
            }
        }
    }
}
