# Jekyll configuration
name: Informed-Proteomics
description: MSPathFinder is a database search engine for top-down proteomics, part of the Informed Proteomics package.
url: https://pnnl-comp-mass-spec.github.io/Informed-Proteomics/
