// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parenthese not needed", Scope = "member", Target = "~M:InformedProteomics.Backend.MassSpecData.PbfLcMsRun.GetOffset(System.Double,System.Double,System.Int64,System.Int64)~System.Int64")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parenthese not needed", Scope = "member", Target = "~M:InformedProteomics.Backend.MassSpecData.PbfLcMsRun.GetPbfFile(System.String,InformedProteomics.Backend.MassSpecData.IMassSpecDataReader,System.String,System.IProgress{PRISM.ProgressData},System.Boolean,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parenthese not needed", Scope = "member", Target = "~M:InformedProteomics.Backend.MassSpecData.PbfLcMsRun.GetXicPointsWithin(System.Double,System.Double,System.Int64,System.Int64,System.Int64)~InformedProteomics.Backend.Data.Spectrometry.Xic")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parenthese not needed", Scope = "member", Target = "~M:InformedProteomics.Backend.MassSpecData.PbfLcMsRun.ReadMetaInfo~System.Boolean")]
[assembly: SuppressMessage("Readability", "RCS1123:Add parentheses when necessary.", Justification = "Parenthese not needed", Scope = "member", Target = "~M:InformedProteomics.Backend.MassSpecData.PbfLcMsRun.SplitLcMsPeakLists.#ctor(System.Double,System.Double,System.Int64)")]
[assembly: SuppressMessage("Usage", "RCS1146:Use conditional access.", Justification = "Leave as-is for clarity", Scope = "member", Target = "~M:InformedProteomics.Backend.MassSpecData.ProteoWizardReaderImplementation.ReadSpectrum(System.Int32,System.Boolean)~InformedProteomics.Backend.Data.Spectrometry.Spectrum")]
[assembly: SuppressMessage("Usage", "RCS1146:Use conditional access.", Justification = "Leave as-is for readability", Scope = "member", Target = "~M:InformedProteomics.Backend.MassSpecData.PbfLcMsRun.BuildPbfFile(System.String,InformedProteomics.Backend.MassSpecData.IMassSpecDataReader,System.String,System.String,System.IProgress{PRISM.ProgressData},System.Boolean,System.Int32,System.Int32)")]
[assembly: SuppressMessage("Usage", "RCS1236:Use exception filter.", Justification = "Leave as-is", Scope = "member", Target = "~M:InformedProteomics.Backend.MassSpecData.PbfLcMsRun.ConvertToPbf(System.String,InformedProteomics.Backend.MassSpecData.IMassSpecDataReader,System.String,System.IProgress{PRISM.ProgressData})~System.String")]
[assembly: SuppressMessage("Usage", "RCS1246:Use element access.", Justification = "Prefer to use .First()", Scope = "member", Target = "~M:InformedProteomics.Backend.MassSpecData.PbfLcMsRun.GetPrecursorChromatogramRange(System.Double,System.Double)~InformedProteomics.Backend.Data.Spectrometry.Xic")]
[assembly: SuppressMessage("Usage", "RCS1246:Use element access.", Justification = "Prefer to use .First()", Scope = "member", Target = "~M:InformedProteomics.Backend.MassSpecData.PbfLcMsRun.GetPrecursorExtractedIonChromatogram(System.Double,System.Double)~InformedProteomics.Backend.Data.Spectrometry.Xic")]
